### ISSUE TITLE
params function not working in post

### ISSUE THREAD

**Issue by masfoobar** [NalaGinrut/artanis#39]
In a past commit of artanis, I noticed you could get post data using, for example, (params rc "email") -- where "email" is an input in a form, etc. In the current release of artanis, I noticed params only appears to work for get request, but not for post.

for example, this is fine: -
(get "/hello/:who" (lambda (rc) (format #f "<p>hello ~a</p> " (params rc "who"))))

However, when setup for (post ...), the params functions returns #f.

I have not seen an example where I could get post data in the documentation, or in the examples. Is there another method to get post data -- or is this is a bug?

Apologies if there is an answer to this. I was unable to find it. I have tried to look around in the artanis source but was unsuccessful due to my current knowledge of Guile (although it is getting better!)

Regards,
masfoobar

**Comment by NalaGinrut** [comment]
@masfoobar  Yes, in the latest version, 'params' only get values from query-string and URL-binding. I intended to remove POST data part.
There're various ways to get values from POST data. The simplest way is #:from-post.
Please see blog.scm in example:
https://github.com/NalaGinrut/artanis/blob/master/examples/blog.scm#L53

**Comment by masfoobar** [comment]
Thanks NalaGinrut.... I appear to have missed that though I likely confused this for something else. I will give this a try shortly.

Thanks again -- and for the quick response!

**Comment by NalaGinrut** [comment]
@masfoobar np ;-)

**Comment by masfoobar** [comment]
Confirming :from-post has solve my problem (as I am sure you knew!)
Thank you!
