### ISSUE TITLE
using artanis, how should I serve the index.html in the repo of cosh properly ?

### ISSUE THREAD

**Issue by xieyuheng** [NalaGinrut/artanis#43]
--------------------------

the repo is here:
https://github.com/coshMain/coshMain.github.io/

--------------------------

I tryed to use the following code to run it:

```scheme

#!/bin/env guile
!#

(use-modules (artanis artanis))

(init-server)

(get "/build"
     (lambda (rc)
       (emit-response-with-file
        "index.html")))

(run #:port 8080)

```

but it reports

         TypeError: Error.captureStackTrace is not a function

--------------------------

while when trying to use other http sever such as

        (1) python -m http.server

        (2) https://github.com/skeeto/emacs-web-server

to run it

cosh runs smoothly as it is on http://coshmain.github.io/

--------------------------

**Comment by NalaGinrut** [comment]
What's your Guile version?

**Comment by NalaGinrut** [comment]
I have no any problem here. Guile-2.0.11

**Comment by xieyuheng** [comment]
Guile-2.0.11

**Comment by xieyuheng** [comment]
------------------------------------

good one :

![good](https://img.vim-cn.com/19/afe422c2d9cf43a3e7b096fff6665fd233055f.png)

------------------------------------

bad ones :

![bad1](https://img.vim-cn.com/64/3e0182a5c6376a1f190c2a1368df9a237b1962.png)

![bad2](https://img.vim-cn.com/4c/9bd8816a0375c2ce9af53d206b1017a44fd52d.png)


------------------------------------

**Comment by NalaGinrut** [comment]
where's the report throws? a screenshot would be better

**Comment by NalaGinrut** [comment]
please add "*.md" as auto emit static file.
```
(init-server #:statics '(png jpg jpeg ico html js css md)) 
```

**Comment by xieyuheng** [comment]
it cool now :)
