### ISSUE TITLE
new applications inside dev project tree (without global installation)

### ISSUE THREAD

**Issue by 11111000000** [NalaGinrut/artanis#47]
Please, describe how to setup development environment with cloned github version of artanis without global installation of anything. I.e. like *lambdanative* approach - new applications inside `apps` folder, thats use current development  version of artanis library and artanis.conf from project root.

**Comment by amirouche** [comment]
I think this will be explained when the tutorial will land. I tried myself to start a project. But there is so many components mvc, migrations and middlewares? That I could not find my way. I think an **example application** would be very nice. If it is possible to have a very minimal application with a model and a couple a views, I will gladly contribute to improve it. For instance a minimal CMS from which an admin an interface can be started. WDYT?

**Comment by amirouche** [comment]
There is examples application in the application folder, but they use mysql :/

**Comment by NalaGinrut** [comment]
Yes, there's local conf in the application folder, you don't have to use the global one.
And I don't have time to support postgresql/sqlite3 in models/migrations, although most of the SQL is compatible, there must be some extra work to support each DB.
Anyway, I will make sure MySQL is workable in next release. And leave the rest in the later version.
