### ISSUE TITLE
"make install" does not work well for packagers

### ISSUE THREAD

**Issue by stefanhusmann** [NalaGinrut/artanis#51]
Hello, 

I tried to create a package for Arch Linux' AUR for artanis, but the make install step does not work for me. There is no support for the DESTDIR variable used by many projects to allow the copy of the needed files into a destination other than the end destination defined by $PREFIX.

I wonder how the obviously existing debian packages were made?

It would also help to have a list of the files which should land in a package, but of course a "make install" step would be the nicer solution.

**Comment by stefanhusmann** [comment]
I opened a pull request with a patch.

**Comment by NalaGinrut** [comment]
Fixed in 308f3419fa, closed,
