### ISSUE TITLE
QueryString parser

### ISSUE THREAD

**Issue by amirouche** [NalaGinrut/artanis#53]
If I'm not mistaken there is not querystring parser in Guile nor Artanis so far. I started an implementation. It's based on Python 3.5 implementation, I've dropped the utf-8 code as I'm not sure what the code does in this area. It don't supported nested dictionaries like https://github.com/bernii/querystring-parser/ but support multiple valued fields and hex values.

The main procedure is a `querystring` it returns an assoc of lists.

Here is the current implementation:

```scheme
(define-module (querystring))

(use-modules (srfi srfi-1))
(use-modules (srfi srfi-26))

(use-modules (ice-9 match))


(define (string-replace string char value)
  (string-map (lambda (<>) (if (eq? <> char) value <>)) string))


(define (spacy string) (string-replace string #\+ #\space))


(define (hex->char a b)
  (integer->char (string->number (list->string (list a b)) 16)))


(define (unhex string)
  (if (not (string-index string #\%))
      string
      (let loop ((chars (string->list string))
                 (out '()))
        (match chars
          ((#\% a b . rest) (loop rest (cons (hex->char a b) out)))
          ((a . rest) (loop rest (cons a out)))
          (() (list->string (reverse out)))))))

(define decode (compose unhex spacy))


(define (acons-list k v alist)
  (let ((value (assoc-ref alist k)))
    (if value
        (let ((alist (alist-delete k alist)))
          (acons k (cons v value) alist))
        (acons k (list v) alist))))

(define (list->alist lst)
  (let next ((lst lst)
             (out '()))
    (if (null? lst)
        out
        (next (cdr lst) (acons-list (caar lst) (cdar lst) out)))))


(define-public (querystring string)
  ;; semi-colon and amp can be used as pair separator
  (define pairs (map (cut string-split <> #\=)
                     (append-map (cut string-split <> #\;) (string-split string #\&))))
  (list->alist (map (match-lambda ((key value) (cons (decode key) (decode value)))) pairs)))


(pk (querystring "abc=1%202+3&d+ef=987&xxx=yyy&xxx=zzz"))
```

**Comment by NalaGinrut** [comment]
However the 'param' function does this for you, although URL-binding comes first.

**Comment by amirouche** [comment]
Sorry for the noise.

**Comment by amirouche** [comment]
Ok I found the code. But how do you manage QS passed in request body? Also the code I'm looking at in `init-query!` does not handle `%` escaping.

**Comment by NalaGinrut** [comment]
For security, we're not going to escape % when data comes in. Only escape it when send them to client.
It's one of protects to avoid SQL-injection.

And the body data should be handled by #:from-body

**Comment by amirouche** [comment]
I need to create a test to be sure. My understanding is that both querystring params in request body and in path must be % escaped.

**Comment by NalaGinrut** [comment]
See here:
https://github.com/NalaGinrut/artanis/blob/master/SECURITY_WARNING#L10

**Comment by amirouche** [comment]
If values are properly escaped before being fed to DB I don't see why it should not be possible to have arbitrary values in the values. The problem is that it breaks other features. Otherwise I would be good with the feature.

**Comment by NalaGinrut** [comment]
Users may escape the string if they really know what they are doing. Artanis won't stop them, but it won't escape for them inexplicitly.
