### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by stefanhusmann** [NalaGinrut/artanis#61]
Hello,

one of the last commits results in the following compile log.

autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.

Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/bin/automake line 3936.
automake (GNU automake) 1.15
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.

libtoolize (GNU libtool) 2.4.6
Written by Gary V. Vaughan <gary@gnu.org>, 2003

Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

m4 (GNU M4) 1.4.17
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Rene' Seindal.

flex 2.6.0

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: configure.ac: not using Automake
autoreconf: Leaving directory `.'
Now run configure and make.
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for gawk... gawk
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking whether make sets $(MAKE)... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking for inline... inline
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for pid_t... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for memchr... yes
checking for mkdir... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
configure: checking for guile 2.0
configure: found guile 2.0
checking for GUILE... yes
checking for guile-config... /usr/bin/guile-config
checking for guile... /usr/bin/guile
checking for guile-config... /usr/bin/guile-config
checking for guile-tools... /usr/bin/guile-tools
checking libguile compile flags... -pthread -I/usr/include/guile/2.0
checking libguile link flags... -lguile-2.0 -lgc
checking for Guile site directory... /usr/share/guile/site
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1635000
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for shl_load... no
checking for shl_load in -ldld... no
checking for dlopen... no
checking for dlopen in -ldl... yes
checking whether a program can dlopen itself... yes
checking whether a statically linked program can dlopen itself... no
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
configure: creating ./config.status
config.status: creating Makefile
config.status: creating bin/art
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing libtool commands
+ compiling artanis/artanis.scm

+ compiling artanis/session.scm

Generating bin/art

Script started on Wed Feb  3 17:35:45 2016
;;; note: source file /usr/share/guile/2.0/sxml/ssax/input-parse.scm
;;;       newer than compiled /usr/lib/guile/2.0/ccache/sxml/ssax/input-parse.go
;;; found fresh local cache at /home/haawda/.cache/guile/ccache/2.0-LE-8-2.0/usr/share/guile/2.0/sxml/ssax/input-parse.scm.go
WARNING: (artanis session): `define-record-type' imported from both (srfi srfi-9) and (rnrs)
ice-9/boot-9.scm:106:20: In procedure #<procedure 2b349c0 at ice-9/boot-9.scm:97:6 (thrown-k . args)>:
ice-9/boot-9.scm:106:20: Syntax error:
artanis/session.scm:317:2: let: bad let in form (let ((maker)) (cond ((assoc-ref *session-backend-table* (get-conf (quote (session backend)))) => (lambda (maker) (maker))) (else (error (format #f "Invalid session backdend: ~:@(~a~)" (get-conf (quote (session backend))))))))

Script done on Wed Feb  3 17:35:46 2016
Makefile:68: recipe for target 'obj/artanis/session.go' failed
make: *** [obj/artanis/session.go] Error 15
make: *** Waiting for unfinished jobs....
Script started on Wed Feb  3 17:35:45 2016
;;; note: source file /usr/share/guile/2.0/sxml/ssax/input-parse.scm
;;;       newer than compiled /usr/lib/guile/2.0/ccache/sxml/ssax/input-parse.go
;;; found fresh local cache at /home/haawda/.cache/guile/ccache/2.0-LE-8-2.0/usr/share/guile/2.0/sxml/ssax/input-parse.scm.go
;;; note: source file ./artanis/session.scm
;;;       newer than compiled obj/artanis/session.go
;;; note: source file ./artanis/session.scm
;;;       newer than compiled /home/haawda/.cache/guile/ccache/2.0-LE-8-2.0/home/haawda/paketierung/meine_Pakete/artanis-git/src/artanis/artanis/session.scm.go
WARNING: (artanis session): `define-record-type' imported from both (srfi srfi-9) and (rnrs)
ice-9/boot-9.scm:106:20: In procedure #<procedure 24779c0 at ice-9/boot-9.scm:97:6 (thrown-k . args)>:
ice-9/boot-9.scm:106:20: Syntax error:
./artanis/session.scm:317:2: let: bad let in form (let ((maker)) (cond ((assoc-ref *session-backend-table* (get-conf (quote (session backend)))) => (lambda (maker) (maker))) (else (error (format #f "Invalid session backdend: ~:@(~a~)" (get-conf (quote (session backend))))))))

Script done on Wed Feb  3 17:35:46 2016
Makefile:68: recipe for target 'obj/artanis/artanis.go' failed
make: *** [obj/artanis/artanis.go] Error 15

**Comment by NalaGinrut** [comment]
@stefanhusmann 
Oh I'm sorry you're very unlucky to encountered this problem just because I just rewrite the session management, so it doesn't work now. ;-)
This is fixed by my latest commits but hasn't pushed yet.
I'm still working on it.

If you really want to try the latest code, please checkout the previous commits,

**Comment by stefanhusmann** [comment]
Last one working was commit 819 (i.e. 9ad2f8ac780e5fee4dc5c7e61688817b9f9237f2).

**Comment by NalaGinrut** [comment]
now it's fixed.

**Comment by stefanhusmann** [comment]
Thanks, works fine.
